globalHost: spring.dev.com
ingress:
  enabled: true
  host: spring.dev.com

services:
  - name: admin-server
    image: npt1601/admin-server
    tag: latest
    port: 9090
    nodePort: 30673
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-dev.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888

  - name: api-gateway
    image: npt1601/api-gateway
    tag: b3767a8
    port: 8080
    nodePort: 30690
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-dev.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888

  - name: config-server
    image: npt1601/config-server
    tag: latest
    port: 8888
    nodePort: 32704
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-dev.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888

  - name: customers-service
    image: npt1601/customers-service
    tag: latest
    port: 8081
    nodePort: 31820
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-dev.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888

  - name: discovery-server
    image: npt1601/discovery-server
    tag: 14d6387
    port: 8761
    nodePort: 30873
    env:
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888

  - name: genai-service
    image: npt1601/genai-service
    tag: latest
    port: 8084
    nodePort: 30257
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-dev.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888

  - name: tracing-server
    image: openzipkin/zipkin
    tag: latest
    port: 9411
    nodePort: 30097
    env:
      - name: JAVA_OPTS
        value: "-XX:UseSVE=0"

  - name: vets-service
    image: npt1601/vets-service
    tag: latest
    port: 8083
    nodePort: 31400
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-dev.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888

  - name: visits-service
    image: npt1601/visits-service
    tag: latest
    port: 8082
    nodePort: 32006
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-dev.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888
