
globalHost: spring.dev.com
ingress:
  enabled: true
  host: spring.dev.com
services:
  - name: vets-service
    image: npt1601/vets-service
    tag: 97501c9
    port: 8080
  - name: customers-service
    image: npt1601/customers-service
    tag: 02167a8
    port: 8080
  - name: visits-service
    image: npt1601/visits-service
    tag: 02167a8
    port: 8080
  - name: api-gateway
    image: npt1601/api-gateway
    tag: 2dc357e
    port: 8080
    env:
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-dev.svc.cluster.local:8888
  - name: config-server
    image: npt1601/config-server
    tag: f2b80f9
    port: 8080
  - name: discovery-server
    image: npt1601/discovery-server
    tag: 5591717
    port: 8080
  - name: admin-server
    image: npt1601/admin-server
    tag: 02167a8
    port: 8080
  - name: genai-service
    image: npt1601/genai-service
    tag: latest
    port: 8080
