globalHost: spring.dev.com
ingress:
  enabled: true
  host: spring.dev.com
services:
  - name: vets-service
    image: npt1601/vets-service
    tag: latest
    port: 8083
  - name: customers-service
    image: npt1601/customers-service
    tag: latest
    port: 8081
  - name: visits-service
    image: npt1601/visits-service
    tag: latest
    port: 8082
  - name: api-gateway
    image: npt1601/api-gateway
    tag: b3767a8
    port: 8080
  - name: config-server
    image: npt1601/config-server
    tag: latest
    port: 8888
  - name: discovery-server
    image: npt1601/discovery-server
    tag: latest
    port: 8761
  - name: admin-server
    image: npt1601/admin-server
    tag: latest
    port: 9090
  - name: genai-service
    image: npt1601/genai-service
    tag: latest
    port: 8084
