globalHost: spring.staging.com
ingress:
  enabled: true
  host: spring.staging.com
services:
  - name: vets-service
    image: npt1601/vets-service
    tag: C:\jenkins-agent\universal\workspace\staging-config-repo>git describe --tags --match "v*.*.*" --abbrev=0 
v1.2.5
    port: 8083
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-staging.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-staging.svc.cluster.local:8888

  - name: customers-service
    image: npt1601/customers-service
    tag: C:\jenkins-agent\universal\workspace\staging-config-repo>git describe --tags --match "v*.*.*" --abbrev=0 
v1.2.5
    port: 8081
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-staging.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-staging.svc.cluster.local:8888

  - name: visits-service
    image: npt1601/visits-service
    tag: C:\jenkins-agent\universal\workspace\staging-config-repo>git describe --tags --match "v*.*.*" --abbrev=0 
v1.2.5
    port: 8082
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-staging.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-staging.svc.cluster.local:8888

  - name: api-gateway
    image: npt1601/api-gateway
    tag: C:\jenkins-agent\universal\workspace\staging-config-repo>git describe --tags --match "v*.*.*" --abbrev=0 
v1.2.5
    port: 8080
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-staging.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-staging.svc.cluster.local:8888

  - name: config-server
    image: npt1601/config-server
    tag: C:\jenkins-agent\universal\workspace\staging-config-repo>git describe --tags --match "v*.*.*" --abbrev=0 
v1.2.5
    port: 8888
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-staging.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-staging.svc.cluster.local:8888

  - name: discovery-server
    image: npt1601/discovery-server
    tag: C:\jenkins-agent\universal\workspace\staging-config-repo>git describe --tags --match "v*.*.*" --abbrev=0 
v1.2.5
    port: 8761
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-staging.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-staging.svc.cluster.local:8888

  - name: admin-server
    image: npt1601/admin-server
    tag: C:\jenkins-agent\universal\workspace\staging-config-repo>git describe --tags --match "v*.*.*" --abbrev=0 
v1.2.5
    port: 9090
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-staging.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-staging.svc.cluster.local:8888

  - name: genai-service
    image: npt1601/genai-service
    tag: C:\jenkins-agent\universal\workspace\staging-config-repo>git describe --tags --match "v*.*.*" --abbrev=0 
v1.2.5
    port: 8084
    env:
      - name: EUREKA_SERVER_URL
        value: http://discovery-server.petclinic-staging.svc.cluster.local:8761
      - name: CONFIG_SERVER_URL
        value: http://config-server.petclinic-staging.svc.cluster.local:8888

