{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag }}"
          ports:
            - containerPort: {{ .port }}
          env:
          {{- if .env }}
          {{- range .env }}
            - name: {{ .name }}
              value: "{{ .value }}"
          {{- end }}
          {{- end }}
{{- end }}
