apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NPT0116/petclinic-deploy-config.git
    targetRevision: main
    path: charts/petclinic-multiservice-chart
    helm:
      valueFiles:
        - ../../values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # 👈 dòng này là chìa khóa!

    automated:
      prune: true
      selfHeal: true
